### ISSUE TITLE
2.1.6 Release

### ISSUE THREAD

**Issue by langmm** [openalea/deploy#38]
I am preparing the conda-forge recipe for this package, but in order for it to reflect the most recent version (2.1.6), there will need to be a .tar.gz release for 2.1.6 (the most recent one is 2.1.1).

Should I just using 2.1.1 or can a release be made for 2.1.6?

**Comment by pradal** [comment]
I am currently contribution this package (and the others also) to conda-forge.
A long journey...
I will ping you when it will be accepted. Thanks for your suggestions.

**Comment by pradal** [comment]
openalea.deploy is now on conda forge: https://github.com/conda-forge/openalea.deploy-feedstock
