### ISSUE TITLE
Missing pywin32 dependancie install on window

### ISSUE THREAD

**Issue by artzet-s** [openalea/deploy#8]
With install of caribu package, installation fail with "python setup.py develop" with message error "No module named win32gui". 

Every thing is fine, after installation of pywin32 package. 

Probabily is right to add pywin32 as dependacie to deploy package on window OS ?

**Comment by pradal** [comment]
PyWin32 can not be installed using pip or easy_install.
It is installed with OpenAlea Installer or using alea_install.
You can read the doc on:
http://openalea.gforge.inria.fr/dokuwiki/doku.php?id=download:source_distribution#windows
